### ISSUE TITLE
import error （Solved, but can not find the root of the problem）

### ISSUE THREAD

**Issue by Xiaoxiaonull** [DannyVanpoucke/LSSVMlib#3]
ModuleNotFoundError: No module named 'LSSVMRegression' when I import this package
The solution I found is to change
 'from LSSVMRegression import LSSVMRegression'
 to
 'from LSSVMlib.LSSVMRegression import LSSVMRegression'

Maybe my computer system is causing the problem
my  environment is
python 3.7.10
Windows 10

**Comment by DannyVanpoucke** [comment]
Could it be that you copied the LSSVMRegression.py to your project or you are missing one of the __init__.py files (or config.py) file?

Happy to see you found a working solution in the mean time.
