### ISSUE TITLE
numpy.linalg.LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by zzjaxx** [DannyVanpoucke/LSSVMlib#5]
LSSVMRegression.py", line 251
numpy.linalg.LinAlgError: SVD did not converge

**Comment by DannyVanpoucke** [comment]
This is an error thrown by the numpy library. It appears the SVD (singular-value-decomposition) of a matrix did not converge. This generally means there is an issue with the data provided. If you can share the data and a minimal working example of code that causes this error, it could be used to gain insight in why it fails. However, as it stands now, this is not an error of the LS-SVM lib, so I will close this issue. You can reopen it if you want to provide data and a MWE.

**Comment by DannyVanpoucke** [comment]
see comment with issue. Resolved for now.
