### ISSUE TITLE
Neo LS-SVM

### ISSUE THREAD

**Issue by lsorber** [DannyVanpoucke/LSSVMlib#7]
Hi there, since this is one of the very few LS-SVM implementations, I thought you might be interested to know that I've recently released a new LS-SVM package called [Neo LS-SVM](https://github.com/lsorber/neo-ls-svm). The idea is that LS-SVMs have a lot of untapped potential, but that they could use a little more love ❤️ now that most of the attention is going to deep learning and gradient-boosted decision trees. Hope it's useful to you!

**Comment by DannyVanpoucke** [comment]
Thank you for the info. Feel free to link to our repositry from Neo-LS-SVM. Best regards Danny.
